# fly.toml app configuration file generated for datingapp-zengzhijing on 2023-05-05T00:52:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp-zengzhijing"
primary_region = "ord"

[build]
  image = "zhijingzeng/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="ddgtnwvyx"
  CloudinarySettings__ApiKey="562992654639259"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
